### ISSUE TITLE
Problem with react-native 0.65

### ISSUE THREAD

**Issue by vitsy** [madsleejensen/react-native-image-capinsets#23]
Looks like this package don't work in  the react-native 0.65.

09-14 03:15:21.240 29727 29937 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at dk.madslee.imageCapInsets.utils.RCTImageLoaderTask.doInBackground(RCTImageLoaderTask.java:27)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at dk.madslee.imageCapInsets.utils.RCTImageLoaderTask.doInBackground(RCTImageLoaderTask.java:12)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-14 03:15:21.240 29727 29937 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by vitsy** [comment]
sorry problem with  0.60.5, but all ok with 0.55.3

**Comment by NirpE** [comment]
There seems to be pull request to fix that issue, meanwhile you can use this: https://github.com/oferRounds/react-native-image-capinsets

**Comment by mayconmesquita** [comment]
@vitsy I created a repo to fix capinsets on RN v0.59, v0.60 and above.
I created a manual linking guide there.
